#############################################################################
# Makefile for building: qgv-box2d
# Generated by qmake (2.01a) (Qt 4.6.3) on: Fri Feb 26 17:58:21 2010
# Project:  qgv-box2d.pro
# Template: app
# Command: /home/ahanssen/git/build/qt/bin/qmake -unix -o Makefile qgv-box2d.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../git/qt/mkspecs/linux-g++ -I. -I../git/build/qt/include/QtCore -I../git/build/qt/include/QtGui -I../git/build/qt/include -I../Box2D_v2.0.1/Box2D/Include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/ahanssen/git/build/qt/lib
LIBS          = $(SUBLIBS)  -L/home/ahanssen/Box2D_v2.0.1/Box2D/Source/Gen/float -L/home/ahanssen/git/build/qt/lib -lbox2d -lQtGui -L/home/ahanssen/git/build/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/ahanssen/git/build/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../git/qt/mkspecs/common/g++.conf \
		../git/qt/mkspecs/common/unix.conf \
		../git/qt/mkspecs/common/linux.conf \
		../git/build/qt/mkspecs/qconfig.pri \
		../git/qt/mkspecs/features/qt_functions.prf \
		../git/qt/mkspecs/features/qt_config.prf \
		../git/qt/mkspecs/features/exclusive_builds.prf \
		../git/qt/mkspecs/features/default_pre.prf \
		../git/qt/mkspecs/features/release.prf \
		../git/qt/mkspecs/features/default_post.prf \
		../git/qt/mkspecs/features/warn_on.prf \
		../git/qt/mkspecs/features/qt.prf \
		../git/qt/mkspecs/features/unix/thread.prf \
		../git/qt/mkspecs/features/moc.prf \
		../git/qt/mkspecs/features/resources.prf \
		../git/qt/mkspecs/features/uic.prf \
		../git/qt/mkspecs/features/yacc.prf \
		../git/qt/mkspecs/features/lex.prf \
		../git/qt/mkspecs/features/include_source_dir.prf \
		qgv-box2d.pro
QMAKE_TARGET  = qgv-box2d
DESTDIR       = 
TARGET        = qgv-box2d

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qgv-box2d.pro  ../git/qt/mkspecs/linux-g++/qmake.conf ../git/qt/mkspecs/common/g++.conf \
		../git/qt/mkspecs/common/unix.conf \
		../git/qt/mkspecs/common/linux.conf \
		../git/build/qt/mkspecs/qconfig.pri \
		../git/qt/mkspecs/features/qt_functions.prf \
		../git/qt/mkspecs/features/qt_config.prf \
		../git/qt/mkspecs/features/exclusive_builds.prf \
		../git/qt/mkspecs/features/default_pre.prf \
		../git/qt/mkspecs/features/release.prf \
		../git/qt/mkspecs/features/default_post.prf \
		../git/qt/mkspecs/features/warn_on.prf \
		../git/qt/mkspecs/features/qt.prf \
		../git/qt/mkspecs/features/unix/thread.prf \
		../git/qt/mkspecs/features/moc.prf \
		../git/qt/mkspecs/features/resources.prf \
		../git/qt/mkspecs/features/uic.prf \
		../git/qt/mkspecs/features/yacc.prf \
		../git/qt/mkspecs/features/lex.prf \
		../git/qt/mkspecs/features/include_source_dir.prf \
		/home/ahanssen/git/build/qt/lib/libQtGui.prl \
		/home/ahanssen/git/build/qt/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile qgv-box2d.pro
../git/qt/mkspecs/common/g++.conf:
../git/qt/mkspecs/common/unix.conf:
../git/qt/mkspecs/common/linux.conf:
../git/build/qt/mkspecs/qconfig.pri:
../git/qt/mkspecs/features/qt_functions.prf:
../git/qt/mkspecs/features/qt_config.prf:
../git/qt/mkspecs/features/exclusive_builds.prf:
../git/qt/mkspecs/features/default_pre.prf:
../git/qt/mkspecs/features/release.prf:
../git/qt/mkspecs/features/default_post.prf:
../git/qt/mkspecs/features/warn_on.prf:
../git/qt/mkspecs/features/qt.prf:
../git/qt/mkspecs/features/unix/thread.prf:
../git/qt/mkspecs/features/moc.prf:
../git/qt/mkspecs/features/resources.prf:
../git/qt/mkspecs/features/uic.prf:
../git/qt/mkspecs/features/yacc.prf:
../git/qt/mkspecs/features/lex.prf:
../git/qt/mkspecs/features/include_source_dir.prf:
/home/ahanssen/git/build/qt/lib/libQtGui.prl:
/home/ahanssen/git/build/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qgv-box2d.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qgv-box2d1.0.0 || $(MKDIR) .tmp/qgv-box2d1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qgv-box2d1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/qgv-box2d1.0.0/ && (cd `dirname .tmp/qgv-box2d1.0.0` && $(TAR) qgv-box2d1.0.0.tar qgv-box2d1.0.0 && $(COMPRESS) qgv-box2d1.0.0.tar) && $(MOVE) `dirname .tmp/qgv-box2d1.0.0`/qgv-box2d1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qgv-box2d1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: main.moc
compiler_moc_source_clean:
	-$(DEL_FILE) main.moc
main.moc: main.cpp
	/home/ahanssen/git/build/qt/bin/moc $(DEFINES) $(INCPATH) main.cpp -o main.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_source_clean 

####### Compile

main.o: main.cpp main.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

